name: 'Pronto'
description: 'Run pronto for the current PR'
inputs:
  github_token:
    description: 'Token to use for reporting'
    required: true
runs:
  using: 'docker'
  image: 'docker://docker.pkg.github.com/wtag/pronto-action/pronto-action:latest'
  args:
    - ${{ inputs.github_token }}
